# Generated by Django 6.0.4 on 2026-06-09 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('NO_CATALOGO', 'No Catalogo')], default='NO_CATALOGO', max_length=20)),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios', verbose_name='Usuário Responsável')),
            ],
        ),
    ]
